-- ============================================================
-- Migraatio: Rodut ja värit lookup-tauluiksi
-- Aja phpMyAdminissa kun schema.sql on jo ajettu aiemmin
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

-- ------------------------------------------------------------
-- 1. Luo breeds-taulu jos ei vielä ole
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `breeds` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `abbreviation` VARCHAR(100) DEFAULT NULL COMMENT 'Lyhenne',
  `is_rare` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = harvinainen rotu',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_breed_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 2. Luo colors-taulu jos ei vielä ole
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `colors` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `abbreviation` VARCHAR(100) DEFAULT NULL COMMENT 'Lyhenne',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_color_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 3. Lisää breed_id sarake horses-tauluun (MySQL 8.0 -yhteensopiva)
-- ------------------------------------------------------------
SET @c1 = (SELECT COUNT(*) FROM information_schema.columns
           WHERE table_schema = DATABASE() AND table_name = 'horses' AND column_name = 'breed_id');
SET @s1 = IF(@c1 = 0,
    'ALTER TABLE `horses` ADD COLUMN `breed_id` INT UNSIGNED DEFAULT NULL',
    'SELECT ''breed_id already exists'' AS info');
PREPARE stmt FROM @s1; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @c2 = (SELECT COUNT(*) FROM information_schema.columns
           WHERE table_schema = DATABASE() AND table_name = 'horses' AND column_name = 'color_id');
SET @s2 = IF(@c2 = 0,
    'ALTER TABLE `horses` ADD COLUMN `color_id` INT UNSIGNED DEFAULT NULL',
    'SELECT ''color_id already exists'' AS info');
PREPARE stmt FROM @s2; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ------------------------------------------------------------
-- 4. Lisää FK-rajoitteet jos ei vielä ole
-- ------------------------------------------------------------
SET @fk1 = (SELECT COUNT(*) FROM information_schema.table_constraints
            WHERE constraint_schema = DATABASE() AND table_name = 'horses' AND constraint_name = 'fk_horses_breed');
SET @s3 = IF(@fk1 = 0,
    'ALTER TABLE `horses` ADD CONSTRAINT `fk_horses_breed` FOREIGN KEY (`breed_id`) REFERENCES `breeds` (`id`) ON DELETE SET NULL',
    'SELECT ''fk_horses_breed already exists'' AS info');
PREPARE stmt FROM @s3; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @fk2 = (SELECT COUNT(*) FROM information_schema.table_constraints
            WHERE constraint_schema = DATABASE() AND table_name = 'horses' AND constraint_name = 'fk_horses_color');
SET @s4 = IF(@fk2 = 0,
    'ALTER TABLE `horses` ADD CONSTRAINT `fk_horses_color` FOREIGN KEY (`color_id`) REFERENCES `colors` (`id`) ON DELETE SET NULL',
    'SELECT ''fk_horses_color already exists'' AS info');
PREPARE stmt FROM @s4; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ------------------------------------------------------------
-- 5. Poista vanhat tekstisarakkeet (MySQL 8.0 -yhteensopiva)
-- ------------------------------------------------------------
SET @db = (SELECT COUNT(*) FROM information_schema.columns
           WHERE table_schema = DATABASE() AND table_name = 'horses' AND column_name = 'breed');
SET @sdb = IF(@db > 0, 'ALTER TABLE `horses` DROP COLUMN `breed`', 'SELECT ''breed col not found'' AS info');
PREPARE stmt FROM @sdb; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @dc = (SELECT COUNT(*) FROM information_schema.columns
           WHERE table_schema = DATABASE() AND table_name = 'horses' AND column_name = 'color');
SET @sdc = IF(@dc > 0, 'ALTER TABLE `horses` DROP COLUMN `color`', 'SELECT ''color col not found'' AS info');
PREPARE stmt FROM @sdc; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ------------------------------------------------------------
-- 6. Rotukanta (INSERT IGNORE = turvallinen ajaa useasti)
-- ------------------------------------------------------------
INSERT IGNORE INTO `breeds` (`id`, `name`, `abbreviation`, `is_rare`) VALUES
  (1,   'Ahaltekinhevonen',                         'at',      0),
  (2,   'Amerikanponi',                              'poa',     0),
  (3,   'Arabialainen täysiverinen',                 'ox',      0),
  (4,   'Azteca',                                    'azt',     0),
  (5,   'Clevelandinruunikko',                       'cb',      0),
  (6,   'Englantilainen täysiverinen',               'xx',      0),
  (7,   'Falabella',                                 'falab',   0),
  (8,   'Frederiksborginhevonen',                    'fred',    0),
  (9,   'Kalliovuortenhevonen',                      'rmh',     0),
  (10,  'Knabstrupinhevonen',                        'knn',     0),
  (11,  'Hannoverinhevonen',                         'hann',    0),
  (12,  'Hollanninpuoliverinen',                     'kwpn',    0),
  (13,  'Oldenburginhevonen',                        'old',     0),
  (14,  'Quarterhevonen',                            'qh',      0),
  (15,  'Russian-Based Sport Horse',                 'rbsh',    0),
  (16,  'Saddlebred',                                'sdb',     0),
  (17,  'Shetlanninponi',                            'she',     0),
  (18,  'Suomenhevonen',                             'sh',      0),
  (19,  'Tennesseenwalker',                          'twh',     0),
  (20,  'Terskinhevonen',                            'tersk',   0),
  (21,  'Trakehner',                                 'trak',    0),
  (22,  'Welsh sektio B',                            'wB',      0),
  (23,  'Welsh Part Bred',                           'wpb',     0),
  (24,  'Welsh Mountain',                            'wA',      0),
  (25,  'Welsh sektio C',                            'wC',      0),
  (26,  'Welsh sektio D',                            'wD',      0),
  (27,  'Newforestinponi',                           'nf',      0),
  (28,  'Gotlanninrussi',                            'russ',    0),
  (29,  'Ratsuponi',                                 'rp',      0),
  (30,  'Islanninhevonen',                           'isl',     0),
  (31,  'Suomalainen puoliverinen',                  'fwb',     0),
  (32,  'Gelderlandinhevonen',                       'geldr',   0),
  (33,  'Andalusianhevonen',                         'pre',     0),
  (34,  'Angloarabialainen täysiverinen',            'x',       0),
  (35,  'Connemaranponi',                            'conn',    0),
  (37,  'Appaloosa',                                 'app',     0),
  (38,  'Amerikanravuri',                            'lv',      0),
  (39,  'Budjonnynhevonen',                          'budj',    0),
  (40,  'Friisiläishevonen',                         'fri',     0),
  (41,  'Perchenhevonen',                            'perch',   0),
  (42,  'Kaspianponi',                               'kasp',    0),
  (43,  'Ruotsinpuoliverinen',                       'swb',     0),
  (44,  'Holsteininhevonen',                         'holst',   0),
  (45,  'Lämminveriravuri',                          'lv',      0),
  (46,  'Irlannincob',                               'ic',      0),
  (47,  'Hackney',                                   'hackn',   0),
  (48,  'Westfaleninhevonen',                        'westf',   0),
  (49,  'Furioso',                                   'fur',     0),
  (50,  'Marwarinhevonen',                           'marw',    0),
  (51,  'Pohjoisnorjanponi',                         'pnp',     0),
  (52,  'Paint Horse',                               'ph',      0),
  (53,  'Norjanvuonohevonen',                        'nvh',     0),
  (54,  'Lämminverinen ratsuhevonen (puoliverinen)', 'pv',      0),
  (55,  'Mustangi',                                  'must',    0),
  (56,  'Unkarinpuoliverinen',                       'hwb',     0),
  (57,  'Haflinginhevonen',                          'hafl',    0),
  (58,  'Pintabian',                                 'pintab',  0),
  (59,  'Morganinhevonen',                           'morg',    0),
  (60,  'Eestinhevonen',                             'eest',    0),
  (61,  'Lewitzer',                                  'lew',     0),
  (62,  'Clydesdalenhevonen',                        'clyd',    0),
  (63,  'Dartmoorinponi',                            'dartm',   0),
  (64,  'Lipizzanhevonen',                           'lip',     0),
  (65,  'Pinto',                                     'pinto',   0),
  (66,  'Brandenburginhevonen',                      'brdbg',   0),
  (67,  'Paso Fino',                                 'pf',      0),
  (68,  'Perunpaso',                                 'pp',      0),
  (69,  'Irlannintyöhevonen',                        'idh',     0),
  (70,  'Kisber-felver',                             'kisb',    0),
  (71,  'Ylämaanponi',                               'highl',   0),
  (72,  'Missourinfoxtrotter',                       'mft',     0),
  (73,  'Kanadanhevonen',                            'kan',     0),
  (74,  'Turkmeeninhevonen',                         'turkm',   0),
  (75,  'Kerry Bog Pony',                            'kbp',     0),
  (76,  'Belgianpuoliverinen',                       'bwp',     0),
  (77,  'Tanskanpuoliverinen',                       'dwb',     0),
  (78,  'National Show Horse',                       'nsh',     0),
  (79,  'Dalesponi',                                 'dales',   0),
  (80,  'Pohjoisruotsinhevonen',                     'prh',     0),
  (81,  'American Bashkir Curly',                    'abc',     0),
  (82,  'Mangalarga',                                'manga',   0),
  (83,  'Criollo',                                   'cri',     0),
  (84,  'Berberihevonen',                            'berb',    0),
  (85,  'Hackneyponi',                               'hacknp',  0),
  (86,  'Ariegenponi',                               'arieg',   0),
  (87,  'Lusitano',                                  'lusit',   0),
  (88,  'Camarguenhevonen',                          'camar',   0),
  (89,  'Fellponi',                                  'fell',    0),
  (90,  'Anglo-trakehner',                           'a-trak',  0),
  (91,  'Amerikanshetlanninponi',                    'amshe',   0),
  (92,  'Exmoorinponi',                              'exm',     0),
  (93,  'Torinhevonen',                              'tori',    0),
  (94,  'Ardennienhevonen',                          'ard',     0),
  (95,  'Belgiantyöhevonen',                         'belg',    0),
  (96,  'Vladimirintyöhevonen',                      'vlad',    0),
  (97,  'Orlovravuri',                               'orlov',   0),
  (98,  'Ranskanravuri',                             'ransk',   0),
  (99,  'Shagya',                                    'sha',     0),
  (100, 'Wielkopolski',                              'wielk',   0),
  (101, 'Venäjänratsuhevonen',                       'vrh',     0),
  (102, 'Tilastohevonen',                            'til',     0),
  (103, 'Sleesianhevonen',                           'slee',    0),
  (104, 'Shirenhevonen',                             'shire',   0),
  (105, 'Nonius',                                    'non',     0),
  (106, 'Huzulponi',                                 'huzul',   0),
  (107, 'Malopolski',                                'malo',    0),
  (108, 'Normandiancob',                             'ncob',    0),
  (109, 'Salernonhevonen',                           'saler',   0),
  (110, 'Boulognenhevonen',                          'boul',    0),
  (111, 'Santelipuuponi',                            'sant',    0),
  (112, 'Noricuminhevonen',                          'norik',   0),
  (113, 'Jakutianponi',                              'jakut',   0),
  (114, 'Morab',                                     'morab',   0),
  (115, 'Australianhevonen',                         'austr',   0),
  (116, 'Novokirgiisi',                              'novok',   0),
  (117, 'Valkovenäjäntyöhevonen',                    'valk',    0),
  (118, 'Baskirianponi',                             'baskir',  0),
  (119, 'Suffolkinhevonen',                          'suff',    0),
  (120, 'Doninhevonen',                              'don',     0),
  (121, 'Ranskanpuoliverinen',                       'sf',      0),
  (122, 'Irlanninpuoliverinen',                      'ihb',     0),
  (123, 'Ukrainanratsuhevonen',                      'ukrh',    0),
  (124, 'Auxois',                                    'aux',     0),
  (125, 'Egyptinhevonen',                            'egypt',   0),
  (126, 'Saarenmaanponi',                            'saare',   0),
  (127, 'Sanhe',                                     'sanhe',   0),
  (128, 'Guangxi',                                   'guang',   0),
  (129, 'Schwarzwaldinrautias',                      'schwa',   0),
  (130, 'American Cream Draft',                      'amc',     0),
  (131, 'Drum Horse',                                'drum',    0),
  (132, 'Misaki',                                    'misak',   0),
  (133, 'Colorado Ranger',                           'colr',    0),
  (134, 'Eteläsaksankylmäverinen',                   'eskv',    0),
  (135, 'Hollannintyöhevonen',                       'holkv',   0),
  (136, 'Altainhevonen',                             'altai',   0),
  (137, 'Lokainponi',                                'lokai',   0),
  (138, 'Iomud',                                     'iomud',   0),
  (139, 'Hesseninhevonen',                           'hesse',   0),
  (140, 'Basutonponi',                               'basuto',  0),
  (141, 'Sveitsinpuoliverinen',                      'chwb',    0),
  (142, 'Deliboz',                                   'delib',   0),
  (143, 'Avellinonponi',                             'avell',   0),
  (144, 'Jyllanninhevonen',                          'jyll',    0),
  (145, 'Sorraianponi',                              'sorr',    0),
  (146, 'Vironpuoliverinen',                         'estpv',   0),
  (147, 'Garranonponi',                              'garra',   0),
  (148, 'Hispano',                                   'hispa',   0),
  (149, 'Tsetsenianvuoristoponi',                    'tsets',   0),
  (150, 'Karpaaninhevonen',                          'karp',    0),
  (151, 'Baijerinhevonen',                           'baij',    0),
  (152, 'Florida Cracker',                           'flacr',   0),
  (153, 'Mecklenburginhevonen',                      'meckl',   0),
  (154, 'Cayuse',                                    'cay',     0),
  (155, 'Amerikanpuoliverinen',                      'amwb',    0),
  (156, 'Freiberginhevonen',                         'freib',   0),
  (157, 'Abessinianhevonen',                         'abess',   0),
  (158, 'Adaev',                                     'adaev',   0),
  (159, 'Bretagnenhevonen',                          'bret',    0),
  (160, 'Alter real',                                'alter',   0),
  (161, 'Jaavanponi',                                'jaav',    0),
  (162, 'Zemaituka',                                 'zhe',     0),
  (163, 'Anglo-kabardinhevonen',                     'a-kab',   0),
  (164, 'Australianponi',                            'austp',   0),
  (165, 'Friesian Sport Horse',                      'fsh',     0),
  (166, 'Batakinponi',                               'batak',   0),
  (167, 'Baskinponi',                                'pottok',  0),
  (168, 'Dülmeninponi',                              'dülm',    0),
  (169, 'Dölehevonen',                               'döle',    0),
  (170, 'Kisonponi',                                 'kiso',    0),
  (171, 'Peneioksenponi',                            'penei',   0),
  (172, 'Maremmanhevonen',                           'marem',   0),
  (173, 'Konik',                                     'konik',   0),
  (174, 'Einsiedelninhevonen',                       'einsi',   0),
  (175, 'Barock Pinto',                              'barock',  0),
  (176, 'Walkaloosa',                                'walkal',  0),
  (177, 'American Miniature Horse',                  'amh',     0),
  (178, 'Ara-appaloosa',                             'ara-ap',  0),
  (179, 'Quarab',                                    'qox',     0),
  (180, 'Pintaloosa',                                'pintl',   0),
  (181, 'Skyroksenponi',                             'skyro',   0),
  (182, 'Padang',                                    'pad',     0),
  (183, 'Hokkaido',                                  'hokk',    0),
  (184, 'Bardianponi',                               'bard',    0),
  (185, 'Sumbanponi',                                'sumb',    0),
  (186, 'Kustanairinhevonen',                        'kustn',   0),
  (187, 'Kabardiini',                                'kabard',  0),
  (188, 'Ban-ei',                                    'ban-ei',  0),
  (189, 'Landesinponi',                              'landes',  0),
  (190, 'Buurinhevonen',                             'buur',    0),
  (191, 'Vjatkanponi',                               'vjatk',   0),
  (192, 'Latvianhevonen',                            'latv',    0),
  (193, 'Karabair',                                  'karab',   0),
  (194, 'Tiibetinponi',                              'tiib',    0),
  (195, 'Gidran',                                    'gid',     0),
  (196, 'Paso Creole',                               'pc',      0),
  (197, 'Chincoteaguenponi',                         'cctg',    0),
  (198, 'Dutch Harness Horse',                       'dhh',     0),
  (199, 'Raskas liettuantyöhevonen',                 'liet',    0),
  (200, 'Eriskaynponi',                              'erisk',   0),
  (201, 'Kladrubinhevonen',                          'klad',    0),
  (202, 'Englanninpuoliverinen',                     'ewb',     0),
  (203, 'Zweibrücker',                               'zweib',   0),
  (204, 'Comtois',                                   'comt',    0),
  (205, 'Reinintyöhevonen',                          'rkv',     0),
  (206, 'Noma',                                      'noma',    0),
  (207, 'Altösterreichisches Warmblut',              'altö',    0),
  (208, 'British Spotted Pony',                      'bsp',     0),
  (209, 'Irish Sport Horse',                         'ish',     0),
  (210, 'Spanish Barb',                              'spb',     0),
  (211, 'Spanish-Norman',                            'spn',     0),
  (212, 'Galiceño',                                  'gcñ',     0),
  (213, 'Spotted Draft Horse',                       'sdh',     0),
  (214, 'Baluchinhevonen',                           'baluch',  0),
  (215, 'Bosnianponi',                               'bosn',    0),
  (216, 'Hackneyarabi',                              'hac-ox',  0),
  (217, 'Saksalainen ratsuhevonen',                  'saksrh',  0),
  (218, 'Arabialainen puoliverinen',                 'awb',     0),
  (219, 'Asturianponi',                              'ast',     0),
  (220, 'Newfoundlandinponi',                        'nfld',    0),
  (221, 'Slovakianpuoliverinen',                     'slvkpv',  0),
  (222, 'Sardinianhevonen',                          'sard',    0),
  (223, 'Spotted Saddle Horse',                      'ssh',     0),
  (224, 'Hunter',                                    'hunter',  0),
  (225, 'Poitounhevonen',                            'poitou',  0),
  (226, 'Raskas neuvostoliitontyöhevonen',           'shd',     0),
  (227, 'Eestin raskas vetohevonen',                 'erv',     0),
  (228, 'Färsaartenponi',                            'färsp',   0),
  (229, 'Badenwürttemberginhevonen',                 'bwürt',   0),
  (230, 'Reininhevonen',                             'rhld',    0),
  (231, 'Slovenianpuoliverinen',                     'slvnpv',  0),
  (232, 'Itävallanpuoliverinen',                     'itävpv',  0),
  (233, 'Itäfriisinhevonen',                         'itäfr',   0),
  (234, 'Tigerhevonen',                              'tiger',   0),
  (235, 'Quarterponi',                               'qp',      0),
  (236, 'Gaited Baroque',                            'gb',      0),
  (237, 'Welara',                                    'welara',  0),
  (238, 'Welara Sport Pony',                         'welsp',   0),
  (239, 'Lippitt Morgan',                            'lpm',     0),
  (241, 'Italiantyöhevonen',                         'tpr',     0),
  (242, 'Euroopan miniatyyrihevonen',                'emh',     0),
  (243, 'Kinskynhevonen',                            'kinsk',   0),
  (244, 'Georgian Grande',                           'gg',      0),
  (245, 'American Walking Pony',                     'awp',     0),
  (246, 'Moriesian',                                 'mories',  0),
  (248, 'Waler',                                     'waler',   0),
  (249, 'Choctaw',                                   'choct',   0),
  (250, 'Tokara',                                    'tokar',   0),
  (251, 'Pottokponi',                                'pottok',  0),
  (252, 'Murgenhevonen',                             'murg',    0),
  (253, 'Sim-Game Sport Horse',                      'sgsh',    0),
  (254, 'Eestin urheiluhevonen',                     'esh',     0),
  (255, 'Muraközinhevonen',                          'murak',   0),
  (256, 'Argentiinanpuoliverinen',                   'arwb',    0),
  (257, 'Brasilianpuoliverinen',                     'brzwb',   0),
  (258, 'Luxemburginpuoliverinen',                   'luxwb',   0),
  (259, 'Saksin-Anhaltinhevonen',                    's-anh',   0),
  (260, 'Pooloponi',                                 'poolo',   0),
  (261, 'Virtuaalinen ratsuponi',                    'vrp',     0),
  (262, 'Trait du Nord',                             'tdn',     0),
  (263, 'Kanadanpuoliverinen',                       'kanpv',   0),
  (264, 'Campolina',                                 'camp',    0),
  (265, 'Nokota',                                    'nok',     0),
  (266, 'Anglo-argentino',                           'a-arg',   0),
  (267, 'Norjanpuoliverinen',                        'nwb',     0),
  (268, 'Sim Sport Pony',                            'ssp',     0),
  (269, 'Sim Sport Warmblood',                       'ssw',     0),
  (270, 'Kylmäveriravuri',                           'kvr',     0),
  (271, 'Raskas venäjäntyöhevonen',                  'rhd',     0),
  (272, 'Zangersheide',                              'Z',       0),
  (273, 'Venäjänravuri',                             'venrav',  0),
  (274, 'Albanianponi',                              'alb',     0),
  (275, 'Puolalainen puoliverinen',                  'pl',      0),
  (276, 'Kathiawarinhevonen',                        'kath',    0),
  (277, 'Dongola',                                   'dong.',   1),
  (278, 'Anastafjahinhevonen',                       'ana',     0),
  (279, 'Italianratsuhevonen',                       'si',      0),
  (281, 'Seepraponi',                                'sepn',    0),
  (282, 'Navarran poni',                             'nav',     0),
  (283, 'Namibialainen puoliverinen',                'nwh',     0),
  (284, 'Aegidienberger',                            'aeg',     0),
  (285, 'Warlander',                                 'war',     0),
  (286, 'Nez Perce Horse',                           'nezph',   0),
  (287, 'Iberian Warmblood',                         'ibw',     0),
  (288, 'American Draft Pony',                       'adp',     0),
  (289, 'Miniature Gypsy Horse',                     'mic',     0),
  (290, 'Arasien',                                   'ara',     0),
  (291, 'Tšekkiläinen puoliverinen',                 'czwb',    0),
  (292, 'Tšekintyöhevonen',                          'tse',     0),
  (299, 'Mongolianhevonen',                          'mong',    0),
  (300, 'Rahvan',                                    'rv',      0),
  (301, 'Espanjalainen puoliverinen',                'sw',      0),
  (302, 'Henson',                                    'hens',    0),
  (303, 'Arabohaflinger',                            'ar-haf',  0),
  (304, 'Meckelnburginkylmäverinen',                 'mecklk',  0),
  (305, 'Posavjenhevonen',                           'pos',     0),
  (306, 'Puolalainen kylmäverinen',                  'plkv',    0),
  (307, 'Ruotsalainen ardennienhevonen',             'rard',    0),
  (308, 'Schleswig-holsteininhevonen',               'schles',  0),
  (309, 'Sloveniankylmäverinen',                     'slvnkv',  0),
  (310, 'Groningeninhevonen',                        'gron',    0),
  (311, 'Saksin-Thüringenin raskas puoliverinen',    'sthür',   0),
  (312, 'Etelä-Afrikan puoliverinen',                'saw',     0),
  (313, 'Sportaloosa',                               'spor',    1),
  (315, 'Andravidanhevonen',                         'ah',      0),
  (316, 'Aasi',                                      'aasi',    0),
  (317, 'Muuli',                                     'muuli',   0),
  (318, 'Sugarbush Draft',                           'sbhd',    0),
  (320, 'Royal Hanoverian Cream',                    'rhc',     0),
  (321, 'Kentucky Mountain Saddle Horse',            'kmsh',    1),
  (322, 'Deutsches Classic-Pony',                    'dcp',     1),
  (323, 'Baiemaro',                                  'bmh',     1);

-- ------------------------------------------------------------
-- 7. Värikanta (INSERT IGNORE = turvallinen ajaa useasti)
-- ------------------------------------------------------------
INSERT IGNORE INTO `colors` (`id`, `name`, `abbreviation`) VALUES
  (1,   'samppanjanruunikko',                        'acha'),
  (2,   'samppanjanruunikonkimo',                    'achakm'),
  (3,   'samppanjanruunikonkirjava',                 'achakrj'),
  (4,   'samppanjanruunikonpäistärikkö',             'achapäis'),
  (5,   'samppanjanruunivoikko',                     'accha'),
  (6,   'samppanjanruunivoikonkimo',                 'acchakm'),
  (7,   'samppanjanruunivoikonkirjava',              'acchakrj'),
  (8,   'samppanjanruunivoikonpäistärikkö',          'acchapäis'),
  (9,   'samppanjanruunihallakko',                   'adcha'),
  (10,  'samppanjanruunihallakonkimo',               'adchakm'),
  (11,  'samppanjanruunihallakonkirjava',            'adchakrj'),
  (12,  'samppanjanruunihallakonpäistärikkö',        'adchapäis'),
  (13,  'samppanjanmusta',                           'clcha'),
  (14,  'samppanjanmustankimo',                      'clchakm'),
  (15,  'samppanjanmustankirjava',                   'clchakrj'),
  (16,  'samppanjanmustanpäistärikkö',               'clchapäis'),
  (17,  'samppanjanmustanvoikko',                    'clccha'),
  (18,  'samppanjanmustanvoikonkimo',                'clcchakm'),
  (19,  'samppanjanmustanvoikonkirjava',             'clcchakrj'),
  (20,  'samppanjanmustanvoikonpäistärikkö',         'clcchapäis'),
  (21,  'samppanjanhiirakko',                        'cldcha'),
  (22,  'samppanjanhiirakonkimo',                    'cldchakm'),
  (23,  'samppanjanhiirakonkirjava',                 'cldchakjr'),
  (24,  'samppanjanhiirakonpäistärikkö',             'cldchapäis'),
  (25,  'cremello',                                  'cre'),
  (26,  'cremellonkimo',                             'crekm'),
  (27,  'cremellonkirjava',                          'crekrj'),
  (28,  'cremellonpäistärikkö',                      'crepäis'),
  (29,  'dominanttivalkoinen',                       'dv'),
  (30,  'samppanjanrautias',                         'gcha'),
  (31,  'samppanjanrautiaankimo',                    'gchakm'),
  (32,  'samppanjanrautiaankirjava',                 'gchakrj'),
  (33,  'samppanjanrautiaanpäistärikkö',             'gchapäis'),
  (34,  'samppanjanvoikko',                          'gccha'),
  (35,  'samppanjanvoikonkimo',                      'gcchakm'),
  (36,  'samppanjanvoikonkirjava',                   'gcchakrj'),
  (37,  'samppanjanvoikonpäistärikkö',               'gcchapäis'),
  (38,  'samppanjanpunahallakko',                    'gdcha'),
  (39,  'samppanjanpunahallakonkimo',                'gdchakm'),
  (40,  'samppanjanpunahallakonkirjava',             'gdchakrj'),
  (41,  'samppanjanpunahallakonpäistärikkö',         'gdchapäis'),
  (46,  'hiirakko',                                  'vm'),
  (47,  'hiirakonkimo',                              'vmkm'),
  (48,  'hiirakonkirjava',                           'vmkrj'),
  (49,  'hiirakonpäistärikkö',                       'vmpäis'),
  (50,  'hopeanhiirakko',                            'hpvm'),
  (51,  'hopeanhiirakonkimo',                        'hpvmkm'),
  (52,  'hopeanhiirakonkirjava',                     'hpvmkrj'),
  (53,  'hopeanhiirakonpäistärikkö',                 'hpvmpäis'),
  (54,  'hopeanmusta',                               'hpm'),
  (55,  'hopeanmustankimo',                          'hpmkm'),
  (56,  'hopeanmustankirjava',                       'hpmkrj'),
  (57,  'hopeanmustanpäistärikkö',                   'hpmpäis'),
  (58,  'hopeanmustanvoikko',                        'hpmvkk'),
  (59,  'hopeanmustanvoikonkimo',                    'hpmvkkokm'),
  (60,  'hopeanmustanvoikonkirjava',                 'hpmvkkokrj'),
  (61,  'hopeanmustanvoikonpäistärikkö',             'hpmvkkopäis'),
  (62,  'hopeanruunikko',                            'hprn'),
  (63,  'hopeanruunikonkimo',                        'hprnkm'),
  (64,  'hopeanruunikonkirjava',                     'hprnkrj'),
  (65,  'hopeanruunikonpäistärikkö',                 'hprnpäis'),
  (66,  'hopeanruunihallakko',                       'hprnhkko'),
  (67,  'hopeanruunihallakonkimo',                   'hprnhkkokm'),
  (68,  'hopeanruunihallakonkirjava',                'hprnhkkokrj'),
  (69,  'hopeanruunihallakonpäistärikkö',            'hprnhkkopäis'),
  (70,  'hopeanruunivoikko',                         'hprnvkk'),
  (71,  'hopeanruunivoikonhallakko',                 'hprnvkkohkko'),
  (72,  'hopeanruunivoikonhallakonkimo',             'hprnvkkohkkokm'),
  (73,  'hopeanruunivoikonhallakonkirjava',          'hprnvkkohkkokrj'),
  (74,  'hopeanruunivoikonhallakonpäistärikkö',      'hprnvkkohkkopäis'),
  (75,  'hopeanruunivoikonkimo',                     'hprnvkkokm'),
  (76,  'hopeanruunivoikonkirjava',                  'hprnvkkokrj'),
  (77,  'hopeanruunivoikonpäistärikkö',              'hprnvkkopäis'),
  (78,  'kanelirautias',                             'krt'),
  (79,  'kimo',                                      'km'),
  (80,  'kulorautias',                               'klrt'),
  (81,  'kärpäskimo',                                'kkm'),
  (82,  'lehmänkirjava',                             'krj'),
  (83,  'liinakko',                                  'lkk'),
  (84,  'maksanrautias',                             'mksrt'),
  (85,  'mushroom',                                  'msh'),
  (86,  'mushroominkimo',                            'mshkm'),
  (87,  'mushroominkirjava',                         'mshkrj'),
  (88,  'mushroominpäistärikkö',                     'mshpäis'),
  (89,  'musta',                                     'm'),
  (90,  'mustankimo',                                'mkm'),
  (91,  'mustankimonkirjava',                        'mkmkrj'),
  (92,  'mustankirjava',                             'mkrj'),
  (93,  'mustanpäistärikkö',                         'mpäis'),
  (94,  'mustanpäistärikönkirjava',                  'mpäiskrj'),
  (95,  'mustanruunikko',                            'mrn'),
  (96,  'mustanvoikko',                              'mvkk'),
  (97,  'mustanvoikonkimo',                          'mvkkokm'),
  (98,  'mustanvoikonkirjava',                       'mvkkokrj'),
  (99,  'mustanvoikonpäistärikkö',                   'mvkkopäis'),
  (100, 'perlino',                                   'pe'),
  (101, 'perlinonkimo',                              'pekm'),
  (102, 'perlinonkirjava',                           'pekrj'),
  (103, 'perlinonpäistärikkö',                       'pepäis'),
  (104, 'punahallakko',                              'phkko'),
  (105, 'punahallakonkimo',                          'phkkokm'),
  (106, 'punahallakonkirjava',                       'phkkokrj'),
  (107, 'punahallakonpäistärikkö',                   'phkkopäis'),
  (108, 'punarautias',                               'prt'),
  (109, 'punaruunikko',                              'prn'),
  (110, 'päistärikkö',                               'päis'),
  (111, 'päistärikönkimo',                           'päiskm'),
  (113, 'päistärikönkirjava',                        'päiskrj'),
  (114, 'rautias',                                   'rt'),
  (115, 'rautiaankimo',                              'rtkm'),
  (116, 'rautiaankimonkirjava',                      'rtkmkrj'),
  (117, 'rautiaankirjava',                           'rtkrj'),
  (118, 'rautiaanpäistärikkö',                       'rtpäis'),
  (119, 'rautiaanpäistärikönkirjava',                'rtpäiskrj'),
  (120, 'ruunikko',                                  'rn'),
  (121, 'ruunihallakko',                             'rnhkko'),
  (122, 'ruunihallakonkimo',                         'rnhkkokm'),
  (123, 'ruunihallakonkirjava',                      'rnhkkokrj'),
  (124, 'ruunihallakonpäistärikkö',                  'rnhkkopäis'),
  (125, 'ruunikonkimo',                              'rnkm'),
  (126, 'ruunikonkimonkirjava',                      'rnkrjkm'),
  (127, 'ruunikonkirjava',                           'rnkrj'),
  (128, 'ruunikonpäistärikkö',                       'rnpäis'),
  (129, 'ruunikonpäistärikönkirjava',                'rnpäiskrj'),
  (130, 'ruunivoikko',                               'rnvkk'),
  (131, 'ruunivoikonkimo',                           'rnvkkokm'),
  (132, 'ruunivoikonkirjava',                        'rnvkkokrj'),
  (133, 'ruunivoikonpäistärikkö',                    'rnvkkopäis'),
  (134, 'ruunivoikonhallakko',                       'rnvhkko'),
  (135, 'ruunivoikonhallakonkimo',                   'vhkkokm'),
  (136, 'ruunivoikonhallakonkirjava',                'vhkkokrj'),
  (137, 'ruunivoikonhallakonpäistärikkö',            'rnvhkkopäis'),
  (138, 'savakkorautias',                            'srt'),
  (143, 'tiikerinkirjava',                           'kn'),
  (144, 'tummanpunarautias',                         'tprt'),
  (145, 'tummanpunaruunikko',                        'tprn'),
  (146, 'tummanrautias',                             'trt'),
  (147, 'tummanruunikko',                            'trn'),
  (148, 'vaaleanpunarautias',                        'vprt'),
  (149, 'vaaleanpunaruunikko',                       'vprn'),
  (150, 'vaaleanrautias',                            'vrt'),
  (151, 'vaaleanruunikko',                           'vrn'),
  (152, 'valkovoikko',                               'bec'),
  (153, 'voikko',                                    'vkk'),
  (154, 'voikonhallakko',                            'vhkko'),
  (155, 'voikonkirjava',                             'vkkokrj'),
  (156, 'smoky cream',                               'smoky cream'),
  (157, 'smoky cream kimo',                          'smoky cream km'),
  (158, 'smoky cream päistärikkö',                   'smoky cream päis'),
  (159, 'smoky cream kirjava',                       'smoky cream krj'),
  (160, 'voikonkimo',                                'vkkkm'),
  (161, 'voikonpäistärikkö',                         'vkkpäis'),
  (162, 'kulomusta',                                 'klm'),
  (163, 'musta tiikerinkirjava',                     'mtkkrj'),
  (164, 'rautias tiikerinkirjava',                   'rtkkrj'),
  (166, 'ruunikko tiikerinkirjava',                  'rntkkrj'),
  (167, 'rautiaanpäistärikönkimo',                   'rtpäistkm'),
  (168, 'rautiaanpäistärikönkimonkirjava',           'rtpäistkmkrj'),
  (169, 'mustanpäistärikönkimonkirjava',             'mpäistkmkrj'),
  (170, 'ruunikonpäistärikönkimonkirjava',           'rnpäistkmkrj'),
  (172, 'hopeanruunikonpäistärikönkimo',             'hprnpäiskm'),
  (173, 'hopeanmustankimonkirjava',                  'hpmkmkrj'),
  (174, 'hopeanruunikonkimonkirjava',                'hprnkmkrj'),
  (175, 'voikonkimonkirjava',                        'vkkokmkrj'),
  (176, 'hiirakonpäistärikönkirjava',                'vmpäiskrj'),
  (177, 'ruunikonpäistärikönkimo',                   'rnpäiskm'),
  (178, 'sysirautias',                               'sysrt'),
  (179, 'rautias mushroom',                          'rtmsh'),
  (181, 'ruunikko mushroom',                         'rnmsh'),
  (182, 'musta mushroom',                            'mmsh'),
  (183, 'voikonhallakonkirjava',                     'vkkhkkokrj'),
  (184, 'voikonpäistärikönkimo',                     'vkkopäistkm'),
  (185, 'voikonhallakonpäistärikkö',                 'vhkkopäis'),
  (186, 'voikonhiirakko',                            'vkkvm'),
  (187, 'Hopeanrautias',                             'hprt'),
  (188, 'hopeanvoikko',                              'hpvkko'),
  (189, 'hopeanvoikonkimo',                          'hpvkkokm'),
  (190, 'hopeanrautiaankimo',                        'hprtkm'),
  (191, 'mustanpäistärikönkimo',                     'mpäiskm'),
  (192, 'tummanruunikonpäistärikkö',                 'trnpäis'),
  (193, 'ruunikko pearl',                            'rnprl'),
  (194, 'rautias pearl',                             'rtprl'),
  (195, 'musta pearl',                               'mprl'),
  (196, 'kirjava pearl',                             'krjprl'),
  (197, 'ruunikonkirjava pearl',                     'rnkrjprl'),
  (198, 'rautiaankirjava pearl',                     'rtkrjprl'),
  (199, 'mustankirjava pearl',                       'mkrjprl'),
  (200, 'mustanvoikonhallakko',                      'mvkkhkko'),
  (201, 'mustanvoikonhallakonkimo',                  'mvkkhkkokm'),
  (202, 'cremellonhallakko',                         'crehkko');

SET FOREIGN_KEY_CHECKS = 1;
