-- ============================================================
-- Virtuaalitalli — Testidata
-- Aja schema.sql:n jälkeen!
-- ============================================================

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- ------------------------------------------------------------
-- Lajit (disciplines)
-- ------------------------------------------------------------
INSERT IGNORE INTO `disciplines` (`id`,`name`,`abbreviation`) VALUES
  (1,  'esteratsastus',      're.'),
  (2,  'kouluratsastus',     'ko.'),
  (3,  'kenttäratsastus',    'kent.'),
  (4,  'matkaratsastus',     'matk.'),
  (5,  'lännenratsastus',    'länn.'),
  (6,  'valjakkoajo',        'valj.'),
  (7,  'askellajiratsastus', 'askel'),
  (8,  'ravit',              'ravit'),
  (9,  'työhevosajo',        'työh.'),
  (10, 'laukat',             'lauk.'),
  (11, 'poniravit',          'pora'),
  (12, 'maastoeste',         'me'),
  (13, 'näyttelyt',          'n.');

-- ------------------------------------------------------------
-- Tasot (levels)
-- ------------------------------------------------------------
INSERT IGNORE INTO `levels` (`name`) VALUES
  ('Harrastaja'),('Alkeis'),('Helppo'),('Keskiluokka'),
  ('Vaikea'),('Kilpa'),('Eliitti');

-- ------------------------------------------------------------
-- Rodut
-- ------------------------------------------------------------
INSERT IGNORE INTO `breeds` (`id`,`name`,`abbreviation`,`is_rare`) VALUES
(323,'Baiemaro','bmh',1),
(322,'Deutsches Classic-Pony','dcp',1),
(321,'Kentucky Mountain Saddle Horse','kmsh',1),
(320,'Royal Hanoverian Cream','rhc',0),
(318,'Sugarbush Draft','sbhd',0),
(317,'Muuli','muuli',0),
(316,'Aasi','aasi',0),
(315,'Andravidanhevonen','ah',0),
(313,'Sportaloosa','spor',1),
(312,'Etelä-Afrikan puoliverinen','saw',0),
(311,'Saksin-Thüringenin raskas puoliverinen','sthür',0),
(310,'Groningeninhevonen','gron',0),
(309,'Sloveniankylmäverinen','slvnkv',0),
(308,'Schleswig-holsteininhevonen','schles',0),
(307,'Ruotsalainen ardennienhevonen','rard',0),
(306,'Puolalainen kylmäverinen','plkv',0),
(305,'Posavjenhevonen','pos',0),
(304,'Meckelnburginkylmäverinen','mecklk',0),
(303,'Arabohaflinger','ar-haf',0),
(302,'Henson','hens',0),
(301,'Espanjalainen puoliverinen','sw',0),
(300,'Rahvan','rv',0),
(299,'Mongolianhevonen','mong',0),
(298,'Latvialainen puoliverinen','lwb',0),
(292,'Tšekintyöhevonen','tse',0),
(291,'Tšekkiläinen puoliverinen','czwb',0),
(290,'Arasien','ara',0),
(289,'Miniature Gypsy Horse','mic',0),
(288,'American Draft Pony','adp',0),
(287,'Iberian Warmblood','ibw',0),
(286,'Nez Perce Horse','nezph',0),
(285,'Warlander','war',0),
(284,'Aegidienberger','aeg',0),
(283,'Namibialainen puoliverinen','nwh',0),
(282,'Navarran poni','nav',0),
(281,'Seepraponi','sepn',0),
(279,'Italianratsuhevonen','si',0),
(278,'Anastafjahinhevonen','ana',0),
(277,'Dongola','dong.',1),
(276,'Kathiawarinhevonen','kath',0),
(275,'Puolalainen puoliverinen','pl',0),
(274,'Albanianponi','alb',0),
(273,'Venäjänravuri','venrav',0),
(272,'Zangersheide','Z',0),
(271,'Raskas venäjäntyöhevonen','rhd',0),
(270,'Kylmäveriravuri','kvr',0),
(269,'Sim Sport Warmblood','ssw',0),
(268,'Sim Sport Pony','ssp',0),
(267,'Norjanpuoliverinen','nwb',0),
(266,'Anglo-argentino','a-arg',0),
(265,'Nokota','nok',0),
(264,'Campolina','camp',0),
(263,'Kanadanpuoliverinen','kanpv',0),
(262,'Trait du Nord','tdn',0),
(261,'Virtuaalinen ratsuponi','vrp',0),
(260,'Pooloponi','poolo',0),
(259,'Saksin-Anhaltinhevonen','s-anh',0),
(258,'Luxemburginpuoliverinen','luxwb',0),
(257,'Brasilianpuoliverinen','brzwb',0),
(256,'Argentiinanpuoliverinen','arwb',0),
(255,'Muraközinhevonen','murak',0),
(254,'Eestin urheiluhevonen','esh',0),
(253,'Sim-Game Sport Horse','sgsh',0),
(252,'Murgenhevonen','murg',0),
(251,'Pottokponi','pottok',0),
(250,'Tokara','tokar',0),
(249,'Choctaw','choct',0),
(248,'Waler','waler',0),
(246,'Moriesian','mories',0),
(245,'American Walking Pony','awp',0),
(244,'Georgian Grande','gg',0),
(243,'Kinskynhevonen','kinsk',0),
(242,'Euroopan miniatyyrihevonen','emh',0),
(241,'Italiantyöhevonen','tpr',0),
(239,'Lippitt Morgan','lpm',0),
(238,'Welara Sport Pony','welsp',0),
(237,'Welara','welara',0),
(236,'Gaited Baroque','gb',0),
(235,'Quarterponi','qp',0),
(234,'Tigerhevonen','tiger',0),
(233,'Itäfriisinhevonen','itäfr',0),
(232,'Itävallanpuoliverinen','itävpv',0),
(231,'Slovenianpuoliverinen','slvnpv',0),
(230,'Reininhevonen','rhld',0),
(229,'Badenwürttemberginhevonen','bwürt',0),
(228,'Färsaartenponi','färsp',0),
(227,'Eestin raskas vetohevonen','erv',0),
(226,'Raskas neuvostoliitontyöhevonen','shd',0),
(225,'Poitounhevonen','poitou',0),
(224,'Hunter','hunter',0),
(223,'Spotted Saddle Horse','ssh',0),
(222,'Sardinianhevonen','sard',0),
(221,'Slovakianpuoliverinen','slvkpv',0),
(220,'Newfoundlandinponi','nfld',0),
(219,'Asturianponi','ast',0),
(218,'Arabialainen puoliverinen','awb',0),
(217,'Saksalainen ratsuhevonen','saksrh',0),
(216,'Hackneyarabi','hac-ox',0),
(215,'Bosnianponi','bosn',0),
(214,'Baluchinhevonen','baluch',0),
(213,'Spotted Draft Horse','sdh',0),
(212,'Galiceño','gcñ',0),
(211,'Spanish-Norman','spn',0),
(210,'Spanish Barb','spb',0),
(209,'Irish Sport Horse','ish',0),
(208,'British Spotted Pony','bsp',0),
(207,'Altösterreichisches Warmblut','altö',0),
(206,'Noma','noma',0),
(205,'Reinintyöhevonen','rkv',0),
(204,'Comtois','comt',0),
(203,'Zweibrücker','zweib',0),
(202,'Englanninpuoliverinen','ewb',0),
(201,'Kladrubinhevonen','klad',0),
(200,'Eriskaynponi','erisk',0),
(199,'Raskas liettuantyöhevonen','liet',0),
(198,'Dutch Harness Horse','dhh',0),
(197,'Chincoteaguenponi','cctg',0),
(196,'Paso Creole','pc',0),
(195,'Gidran','gid',0),
(194,'Tiibetinponi','tiib',0),
(193,'Karabair','karab',0),
(192,'Latvianhevonen','latv',0),
(191,'Vjatkanponi','vjatk',0),
(190,'Buurinhevonen','buur',0),
(189,'Landesinponi','landes',0),
(188,'Ban-ei','ban-ei',0),
(187,'Kabardiini','kabard',0),
(186,'Kustanairinhevonen','kustn',0),
(185,'Sumbanponi','sumb',0),
(184,'Bardianponi','bard',0),
(183,'Hokkaido','hokk',0),
(182,'Padang','pad',0),
(181,'Skyroksenponi','skyro',0),
(180,'Pintaloosa','pintl',0),
(179,'Quarab','qox',0),
(178,'Ara-appaloosa','ara-ap',0),
(177,'American Miniature Horse','amh',0),
(176,'Walkaloosa','walkal',0),
(175,'Barock Pinto','barock',0),
(174,'Einsiedelninhevonen','einsi',0),
(173,'Konik','konik',0),
(172,'Maremmanhevonen','marem',0),
(171,'Peneioksenponi','penei',0),
(170,'Kisonponi','kiso',0),
(169,'Dölehevonen','döle',0),
(168,'Dülmeninponi','dülm',0),
(167,'Baskinponi','pottok',0),
(166,'Batakinponi','batak',0),
(165,'Friesian Sport Horse','fsh',0),
(164,'Australianponi','austp',0),
(163,'Anglo-kabardinhevonen','a-kab',0),
(162,'Zemaituka','zhe',0),
(161,'Jaavanponi','jaav',0),
(160,'Alter real','alter',0),
(159,'Bretagnenhevonen','bret',0),
(158,'Adaev','adaev',0),
(157,'Abessinianhevonen','abess',0),
(156,'Freiberginhevonen','freib',0),
(155,'Amerikanpuoliverinen','amwb',0),
(154,'Cayuse','cay',0),
(153,'Mecklenburginhevonen','meckl',0),
(152,'Florida Cracker','flacr',0),
(151,'Baijerinhevonen','baij',0),
(150,'Karpaaninhevonen','karp',0),
(149,'Tsetsenianvuoristoponi','tsets',0),
(148,'Hispano','hispa',0),
(147,'Garranonponi','garra',0),
(146,'Vironpuoliverinen','estpv',0),
(145,'Sorraianponi','sorr',0),
(144,'Jyllanninhevonen','jyll',0),
(143,'Avellinonponi','avell',0),
(142,'Deliboz','delib',0),
(141,'Sveitsinpuoliverinen','chwb',0),
(140,'Basutonponi','basuto',0),
(139,'Hesseninhevonen','hesse',0),
(138,'Iomud','iomud',0),
(137,'Lokainponi','lokai',0),
(136,'Altainhevonen','altai',0),
(135,'Hollannintyöhevonen','holkv',0),
(134,'Eteläsaksankylmäverinen','eskv',0),
(133,'Colorado Ranger','colr',0),
(132,'Misaki','misak',0),
(131,'Drum Horse','drum',0),
(130,'American Cream Draft','amc',0),
(129,'Schwarzwaldinrautias','schwa',0),
(128,'Guangxi','guang',0),
(127,'Sanhe','sanhe',0),
(126,'Saarenmaanponi','saare',0),
(125,'Egyptinhevonen','egypt',0),
(124,'Auxois','aux',0),
(123,'Ukrainanratsuhevonen','ukrh',0),
(122,'Irlanninpuoliverinen','ihb',0),
(121,'Ranskanpuoliverinen','sf',0),
(120,'Doninhevonen','don',0),
(119,'Suffolkinhevonen','suff',0),
(118,'Baskirianponi','baskir',0),
(117,'Valkovenäjäntyöhevonen','valk',0),
(116,'Novokirgiisi','novok',0),
(115,'Australianhevonen','austr',0),
(114,'Morab','morab',0),
(113,'Jakutianponi','jakut',0),
(112,'Noricuminhevonen','norik',0),
(111,'Santelipuuponi','sant',0),
(110,'Boulognenhevonen','boul',0),
(109,'Salernonhevonen','saler',0),
(108,'Normandiancob','ncob',0),
(107,'Malopolski','malo',0),
(106,'Huzulponi','huzul',0),
(105,'Nonius','non',0),
(104,'Shirenhevonen','shire',0),
(103,'Sleesianhevonen','slee',0),
(102,'Tilastohevonen','til',0),
(101,'Venäjänratsuhevonen','vrh',0),
(100,'Wielkopolski','wielk',0),
(99,'Shagya','sha',0),
(98,'Ranskanravuri','ransk',0),
(97,'Orlovravuri','orlov',0),
(96,'Vladimirintyöhevonen','vlad',0),
(95,'Belgiantyöhevonen','belg',0),
(94,'Ardennienhevonen','ard',0),
(93,'Torinhevonen','tori',0),
(92,'Exmoorinponi','exm',0),
(91,'Amerikanshetlanninponi','amshe',0),
(90,'Anglo-trakehner','a-trak',0),
(89,'Fellponi','fell',0),
(88,'Camarguenhevonen','camar',0),
(87,'Lusitano','lusit',0),
(86,'Ariegenponi','arieg',0),
(85,'Hackneyponi','hacknp',0),
(84,'Berberihevonen','berb',0),
(83,'Criollo','cri',0),
(82,'Mangalarga','manga',0),
(81,'American Bashkir Curly','abc',0),
(80,'Pohjoisruotsinhevonen','prh',0),
(79,'Dalesponi','dales',0),
(78,'National Show Horse','nsh',0),
(77,'Tanskanpuoliverinen','dwb',0),
(76,'Belgianpuoliverinen','bwp',0),
(75,'Kerry Bog Pony','kbp',0),
(74,'Turkmeeninhevonen','turkm',0),
(73,'Kanadanhevonen','kan',0),
(72,'Missourinfoxtrotter','mft',0),
(71,'Ylämaanponi','highl',0),
(70,'Kisber-felver','kisb',0),
(69,'Irlannintyöhevonen','idh',0),
(68,'Perunpaso','pp',0),
(67,'Paso Fino','pf',0),
(66,'Brandenburginhevonen','brdbg',0),
(65,'Pinto','pinto',0),
(64,'Lipizzanhevonen','lip',0),
(63,'Dartmoorinponi','dartm',0),
(62,'Clydesdalenhevonen','clyd',0),
(61,'Lewitzer','lew',0),
(60,'Eestinhevonen','eest',0),
(59,'Morganinhevonen','morg',0),
(58,'Pintabian','pintab',0),
(57,'Haflinginhevonen','hafl',0),
(56,'Unkarinpuoliverinen','hwb',0),
(55,'Mustangi','must',0),
(54,'Lämminverinen ratsuhevonen (puoliverinen)','pv',0),
(53,'Norjanvuonohevonen','nvh',0),
(52,'Paint Horse','ph',0),
(51,'Pohjoisnorjanponi','pnp',0),
(50,'Marwarinhevonen','marw',0),
(49,'Furioso','fur',0),
(48,'Westfaleninhevonen','westf',0),
(47,'Hackney','hackn',0),
(46,'Irlannincob','ic',0),
(45,'Lämminveriravuri','lv',0),
(44,'Holsteininhevonen','holst',0),
(43,'Ruotsinpuoliverinen','swb',0),
(42,'Kaspianponi','kasp',0),
(41,'Perchenhevonen','perch',0),
(40,'Friisiläishevonen','fri',0),
(39,'Budjonnynhevonen','budj',0),
(38,'Amerikanravuri','lv',0),
(37,'Appaloosa','app',0),
(35,'Connemaranponi','conn',0),
(34,'Angloarabialainen täysiverinen','x',0),
(33,'Andalusianhevonen','pre',0),
(32,'Gelderlandinhevonen','geldr',0),
(31,'Suomalainen puoliverinen','fwb',0),
(30,'Islanninhevonen','isl',0),
(29,'Ratsuponi','rp',0),
(28,'Gotlanninrussi','russ',0),
(27,'Newforestinponi','nf',0),
(26,'Welsh sektio D','wD',0),
(25,'Welsh sektio C','wC',0),
(24,'Welsh Mountain','wA',0),
(23,'Welsh Part Bred','wpb',0),
(22,'Welsh sektio B','wB',0),
(21,'Trakehner','trak',0),
(20,'Terskinhevonen','tersk',0),
(19,'Tennesseenwalker','twh',0),
(18,'Suomenhevonen','sh',0),
(17,'Shetlanninponi','she',0),
(16,'Saddlebred','sdb',0),
(15,'Russian-Based Sport Horse','rbsh',0),
(14,'Quarterhevonen','qh',0),
(13,'Oldenburginhevonen','old',0),
(12,'Hollanninpuoliverinen','kwpn',0),
(11,'Hannoverinhevonen','hann',0),
(10,'Knabstrupinhevonen','knn',0),
(9,'Kalliovuortenhevonen','rmh',0),
(8,'Frederiksborginhevonen','fred',0),
(7,'Falabella','falab',0),
(6,'Englantilainen täysiverinen','xx',0),
(5,'Clevelandinruunikko','cb',0),
(4,'Azteca','azt',0),
(3,'Arabialainen täysiverinen','ox',0),
(2,'Amerikanponi','poa',0),
(1,'Ahaltekinhevonen','at',0);

-- ------------------------------------------------------------
-- Värit
-- ------------------------------------------------------------
INSERT IGNORE INTO `colors` (`id`,`name`,`abbreviation`) VALUES
(202,'cremellonhallakko','crehkko'),
(201,'mustanvoikonhallakonkimo','mvkkhkkokm'),
(200,'mustanvoikonhallakko','mvkkhkko'),
(199,'mustankirjava pearl','mkrjprl'),
(198,'rautiaankirjava pearl','rtkrjprl'),
(197,'ruunikonkirjava pearl','rnkrjprl'),
(196,'kirjava pearl','krjprl'),
(195,'musta pearl','mprl'),
(194,'rautias pearl','rtprl'),
(193,'ruunikko pearl','rnprl'),
(192,'tummanruunikonpäistärikkö','trnpäis'),
(191,'mustanpäistärikönkimo','mpäiskm'),
(190,'hopeanrautiaankimo','hprtkm'),
(189,'hopeanvoikonkimo','hpvkkokm'),
(188,'hopeanvoikko','hpvkko'),
(187,'Hopeanrautias','hprt'),
(186,'voikonhiirakko','vkkvm'),
(185,'voikonhallakonpäistärikkö','vhkkopäis'),
(184,'voikonpäistärikönkimo','vkkopäistkm'),
(183,'voikonhallakonkirjava','vkkhkkokrj'),
(182,'musta mushroom','mmsh'),
(181,'ruunikko mushroom','rnmsh'),
(179,'rautias mushroom','rtmsh'),
(178,'sysirautias','sysrt'),
(177,'ruunikonpäistärikönkimo','rnpäiskm'),
(176,'hiirakonpäistärikönkirjava','vmpäiskrj'),
(175,'voikonkimonkirjava','vkkokmkrj'),
(174,'hopeanruunikonkimonkirjava','hprnkmkrj'),
(173,'hopeanmustankimonkirjava','hpmkmkrj'),
(172,'hopeanruunikonpäistärikönkimo','hprnpäiskm'),
(170,'ruunikonpäistärikönkimonkirjava','rnpäistkmkrj'),
(169,'mustanpäistärikönkimonkirjava','mpäistkmkrj'),
(168,'rautiaanpäistärikönkimonkirjava','rtpäistkmkrj'),
(167,'rautiaanpäistärikönkimo','rtpäistkm'),
(166,'ruunikko tiikerinkirjava','rntkkrj'),
(164,'rautias tiikerinkirjava','rtkkrj'),
(163,'musta tiikerinkirjava','mtkkrj'),
(162,'kulomusta','klm'),
(161,'voikonpäistärikkö','vkkpäis'),
(160,'voikonkimo','vkkkm'),
(159,'smoky cream kirjava','smoky cream krj'),
(158,'smoky cream päistärikkö','smoky cream päis'),
(157,'smoky cream kimo','smoky cream km'),
(156,'smoky cream','smoky cream'),
(155,'voikonkirjava','vkkokrj'),
(154,'voikonhallakko','vhkko'),
(153,'voikko','vkk'),
(152,'valkovoikko','bec'),
(151,'vaaleanruunikko','vrn'),
(150,'vaaleanrautias','vrt'),
(149,'vaaleanpunaruunikko','vprn'),
(148,'vaaleanpunarautias','vprt'),
(147,'tummanruunikko','trn'),
(146,'tummanrautias','trt'),
(145,'tummanpunaruunikko','tprn'),
(144,'tummanpunarautias','tprt'),
(143,'tiikerinkirjava','kn'),
(138,'savakkorautias','srt'),
(137,'ruunivoikonhallakonpäistärikkö','rnvhkkopäis'),
(136,'ruunivoikonhallakonkirjava','vhkkokrj'),
(135,'ruunivoikonhallakonkimo','vhkkokm'),
(134,'ruunivoikonhallakko','rnvhkko'),
(133,'ruunivoikonpäistärikkö','rnvkkopäis'),
(132,'ruunivoikonkirjava','rnvkkokrj'),
(131,'ruunivoikonkimo','rnvkkokm'),
(130,'ruunivoikko','rnvkk'),
(129,'ruunikonpäistärikönkirjava','rnpäiskrj'),
(128,'ruunikonpäistärikkö','rnpäis'),
(127,'ruunikonkirjava','rnkrj'),
(126,'ruunikonkimonkirjava','rnkrjkm'),
(125,'ruunikonkimo','rnkm'),
(124,'ruunihallakonpäistärikkö','rnhkkopäis'),
(123,'ruunihallakonkirjava','rnhkkokrj'),
(122,'ruunihallakonkimo','rnhkkokm'),
(121,'ruunihallakko','rnhkko'),
(120,'ruunikko','rn'),
(119,'rautiaanpäistärikönkirjava','rtpäiskrj'),
(118,'rautiaanpäistärikkö','rtpäis'),
(117,'rautiaankirjava','rtkrj'),
(116,'rautiaankimonkirjava','rtkmkrj'),
(115,'rautiaankimo','rtkm'),
(114,'rautias','rt'),
(113,'päistärikönkirjava','päiskrj'),
(111,'päistärikönkimo','päiskm'),
(110,'päistärikkö','päis'),
(109,'punaruunikko','prn'),
(108,'punarautias','prt'),
(107,'punahallakonpäistärikkö','phkkopäis'),
(106,'punahallakonkirjava','phkkokrj'),
(105,'punahallakonkimo','phkkokm'),
(104,'punahallakko','phkko'),
(103,'perlinonpäistärikkö','pepäis'),
(102,'perlinonkirjava','pekrj'),
(101,'perlinonkimo','pekm'),
(100,'perlino','pe'),
(99,'mustanvoikonpäistärikkö','mvkkopäis'),
(98,'mustanvoikonkirjava','mvkkokrj'),
(97,'mustanvoikonkimo','mvkkokm'),
(96,'mustanvoikko','mvkk'),
(95,'mustanruunikko','mrn'),
(94,'mustanpäistärikönkirjava','mpäiskrj'),
(93,'mustanpäistärikkö','mpäis'),
(92,'mustankirjava','mkrj'),
(91,'mustankimonkirjava','mkmkrj'),
(90,'mustankimo','mkm'),
(89,'musta','m'),
(88,'mushroominpäistärikkö','mshpäis'),
(87,'mushroominkirjava','mshkrj'),
(86,'mushroominkimo','mshkm'),
(85,'mushroom','msh'),
(84,'maksanrautias','mksrt'),
(83,'liinakko','lkk'),
(82,'lehmänkirjava','krj'),
(81,'kärpäskimo','kkm'),
(80,'kulorautias','klrt'),
(79,'kimo','km'),
(78,'kanelirautias','krt'),
(77,'hopeanruunivoikonpäistärikkö','hprnvkkopäis'),
(76,'hopeanruunivoikonkirjava','hprnvkkokrj'),
(75,'hopeanruunivoikonkimo','hprnvkkokm'),
(74,'hopeanruunivoikonhallakonpäistärikkö','hprnvkkohkkopäis'),
(73,'hopeanruunivoikonhallakonkirjava','hprnvkkohkkokrj'),
(72,'hopeanruunivoikonhallakonkimo','hprnvkkohkkokm'),
(71,'hopeanruunivoikonhallakko','hprnvkkohkko'),
(70,'hopeanruunivoikko','hprnvkk'),
(69,'hopeanruunihallakonpäistärikkö','hprnhkkopäis'),
(68,'hopeanruunihallakonkirjava','hprnhkkokrj'),
(67,'hopeanruunihallakonkimo','hprnhkkokm'),
(66,'hopeanruunihallakko','hprnhkko'),
(65,'hopeanruunikonpäistärikkö','hprnpäis'),
(64,'hopeanruunikonkirjava','hprnkrj'),
(63,'hopeanruunikonkimo','hprnkm'),
(62,'hopeanruunikko','hprn'),
(61,'hopeanmustanvoikonpäistärikkö','hpmvkkopäis'),
(60,'hopeanmustanvoikonkirjava','hpmvkkokrj'),
(59,'hopeanmustanvoikonkimo','hpmvkkokm'),
(58,'hopeanmustanvoikko','hpmvkk'),
(57,'hopeanmustanpäistärikkö','hpmpäis'),
(56,'hopeanmustankirjava','hpmkrj'),
(55,'hopeanmustankimo','hpmkm'),
(54,'hopeanmusta','hpm'),
(53,'hopeanhiirakonpäistärikkö','hpvmpäis'),
(52,'hopeanhiirakonkirjava','hpvmkrj'),
(51,'hopeanhiirakonkimo','hpvmkm'),
(50,'hopeanhiirakko','hpvm'),
(49,'hiirakonpäistärikkö','vmpäis'),
(48,'hiirakonkirjava','vmkrj'),
(47,'hiirakonkimo','vmkm'),
(46,'hiirakko','vm'),
(41,'samppanjanpunahallakonpäistärikkö','gdchapäis'),
(40,'samppanjanpunahallakonkirjava','gdchakrj'),
(39,'samppanjanpunahallakonkimo','gdchakm'),
(38,'samppanjanpunahallakko','gdcha'),
(37,'samppanjanvoikonpäistärikkö','gcchapäis'),
(36,'samppanjanvoikonkirjava','gcchakrj'),
(35,'samppanjanvoikonkimo','gcchakm'),
(34,'samppanjanvoikko','gccha'),
(33,'samppanjanrautiaanpäistärikkö','gchapäis'),
(32,'samppanjanrautiaankirjava','gchakrj'),
(31,'samppanjanrautiaankimo','gchakm'),
(30,'samppanjanrautias','gcha'),
(29,'dominanttivalkoinen','dv'),
(28,'cremellonpäistärikkö','crepäis'),
(27,'cremellonkirjava','crekrj'),
(26,'cremellonkimo','crekm'),
(25,'cremello','cre'),
(24,'samppanjanhiirakonpäistärikkö','cldchapäis'),
(23,'samppanjanhiirakonkirjava','cldchakjr'),
(22,'samppanjanhiirakonkimo','cldchakm'),
(21,'samppanjanhiirakko','cldcha'),
(20,'samppanjanmustanvoikonpäistärikkö','clcchapäis'),
(19,'samppanjanmustanvoikonkirjava','clcchakrj'),
(18,'samppanjanmustanvoikonkimo','clcchakm'),
(17,'samppanjanmustanvoikko','clccha'),
(16,'samppanjanmustanpäistärikkö','clchapäis'),
(15,'samppanjanmustankirjava','clchakrj'),
(14,'samppanjanmustankimo','clchakm'),
(13,'samppanjanmusta','clcha'),
(12,'samppanjanruunihallakonpäistärikkö','adchapäis'),
(11,'samppanjanruunihallakonkirjava','adchakrj'),
(10,'samppanjanruunihallakonkimo','adchakm'),
(9,'samppanjanruunihallakko','adcha'),
(8,'samppanjanruunivoikonpäistärikkö','acchapäis'),
(7,'samppanjanruunivoikonkirjava','acchakrj'),
(6,'samppanjanruunivoikonkimo','acchakm'),
(5,'samppanjanruunivoikko','accha'),
(4,'samppanjanruunikonpäistärikkö','achapäis'),
(3,'samppanjanruunikonkirjava','achakrj'),
(2,'samppanjanruunikonkimo','achakm'),
(1,'samppanjanruunikko','acha');

-- ------------------------------------------------------------
-- Admin-käyttäjä (salasana: admin123 — vaihda tuotantoon!)

-- Generoi oikea tiiviste PHP:llä: echo password_hash('oma_salasana', PASSWORD_BCRYPT, ['cost' => 12]);
-- Alla oleva hash on esimerkki — generoi oma ennen tuotantoon siirtoa.
INSERT IGNORE INTO `admin_users` (`username`, `password`) VALUES
  ('admin', '$2y$12$l/XHt42ns9SFcY.NthYsfurFblh97K7DA5bk2QIYusKxA4kYwCfeK');
-- HUOM: Tämä on TESTISALASANA. Generoi uusi tiiviste ennen tuotantoon siirtoa!
-- 173EKfaqdc4F85n66HYs87r9F5g3oC6I

-- Hevonen 1: Isoisä (ulkopuolinen, evm=1, asuu muualla)
INSERT INTO `horses` (`id`, `name`, `slug`, `call_name`, `breed_id`, `birth_date`, `gender`, `color_id`, `evm`, `profile_url`) VALUES
  (1, 'Testiori Suuri', 'testiori-suuri', 'Testi', 18, '2005-03-15', 'ori', 82, 1, 'https://esimerkki.altervista.org/pages/hevonen.php?id=1');

-- Hevonen 2: Isä (ulkopuolinen, asuu muualla)
INSERT INTO `horses` (`id`, `name`, `slug`, `call_name`, `breed_id`, `birth_date`, `gender`, `color_id`, `sire_id`, `evm`, `profile_url`) VALUES
  (2, 'Testijunkkari', 'testijunkkari', 'Junkku', 18, '2012-05-22', 'ori', 114, 1, 1, 'https://esimerkki.altervista.org/pages/hevonen.php?id=2');

-- Hevonen 3: Tämän tallin hevonen (jälkeläinen)
INSERT INTO `horses` (`id`, `name`, `slug`, `call_name`, `breed_id`, `birth_date`, `gender`, `color_id`, `height_cm`, `vh_id`, `discipline_id`, `level_id`, `owner_name`, `owner_email`, `breeder_name`, `sire_id`, `description`, `evm`) VALUES
  (3, 'Testiponi Tähti', 'testiponi-tahti', 'Tähti', 18, '2018-07-10', 'tamma', 120, 145, 'VH-2018-12345', 1, 1, 'Maija Meikäläinen', 'maija@esimerkki.fi', 'Virtanen Oy', 2, 'Rauhallinen ja luotettava tamma. Sopii hyvin aloittelijoille.', 0);

-- Kilpailu testihevoselle
INSERT INTO `competitions` (`horse_id`, `competition_name`, `competition_date`, `organizer`, `class`, `placement`, `points`, `notes`) VALUES
  (3, 'Kevätkilpailu 2024', '2024-05-12', 'Ruusupuiston talli', 'EA', '2.', 85.50, 'Hyvä suoritus, hieman hermostunut alussa.');

-- Tuleva varsa testihevoselle
INSERT INTO `foals` (`horse_id`, `foal_name`, `sire_id`, `dam_id`, `birth_year`, `gender`, `status`) VALUES
  (3, 'Tulevaisuus', 2, 3, 2026, 'tuntematon', 'expected');
